### ISSUE TITLE
Accuracy drop compared to the paper

### ISSUE THREAD

**Issue by lixinghe1999** [swimmiing/ACL-SSL#1]
Dear authors,

Thanks for open-sourcing this project. Generally, the codebase is well organized.
However, I can't get the same or similar number as in the paper. I expect there are some basic mistakes I made.

Below are My "test_rst.txt" on VGGSound dataset, the AP is worse than that of the paper.
`ACL (vggss_test with thr = 0.05)
AP50(cIoU)=30.579964850615116, AUC=36.1779925795743
ACL (vggss_test with thr = 0.1)
AP50(cIoU)=36.711579769576254, AUC=39.26381566100371
ACL (vggss_test with thr = 0.15)
AP50(cIoU)=39.58211286858035, AUC=40.89728568638938
ACL (vggss_test with thr = 0.2)
AP50(cIoU)=41.08572544424917, AUC=41.67350126928334
ACL (vggss_test with thr = 0.25)
AP50(cIoU)=41.59343878148799, AUC=41.87561023237649
ACL (vggss_test with thr = 0.3)
AP50(cIoU)=41.515329037297406, AUC=41.8140988088264
ACL (vggss_test with thr = 0.35)
AP50(cIoU)=41.67154852567858, AUC=41.55828939660222
ACL (vggss_test with thr = 0.4)
AP50(cIoU)=41.49580160124975, AUC=41.17555165006834
ACL (vggss_test with thr = 0.45)
AP50(cIoU)=40.81234133958211, AUC=40.65026362038665
ACL (vggss_test with thr = 0.5)
AP50(cIoU)=39.660222612770944, AUC=40.068346026166765
ACL (vggss_test with thr = 0.55)
AP50(cIoU)=38.6838508103886, AUC=39.41515329037297
ACL (vggss_test with thr = 0.6)
AP50(cIoU)=37.609841827768015, AUC=38.604764694395634
ACL (vggss_test with thr = 0.65)
AP50(cIoU)=36.1452841241945, AUC=37.68892794376099
ACL (vggss_test with thr = 0.7)
AP50(cIoU)=34.876000781097446, AUC=36.6373755125952
ACL (vggss_test with thr = 0.75)
AP50(cIoU)=32.98183948447569, AUC=35.32024995118142
ACL (vggss_test with thr = 0.8)
AP50(cIoU)=30.931458699472756, AUC=33.86447959382934
ACL (vggss_test with thr = 0.85)
AP50(cIoU)=27.514157391134543, AUC=31.9859402460457
ACL (vggss_test with thr = 0.9)
AP50(cIoU)=23.667252489748098, AUC=29.254051942979892
ACL (vggss_test with thr = 0.95)
AP50(cIoU)=16.285881663737552, AUC=23.326498730716654
`
I have attached one of the visualization outputs, and it seems reasonable.
![image](https://github.com/swimmiing/ACL-SSL/assets/60444469/67f75d80-d5ac-4712-947d-061c9e7f228e)

I have a few doubts:
1. I downloaded the VGGSound dataset and extracted the audio, resulting in some "stereo" or "2-channels" audio, so I slightly revised to code always to select the first channel. From my understanding, it shouldn't cause an accuracy drop.
2. I used the VGGSound from huggingface and extended VGGSound from the link you provided, not sure if I am right.
3. I use the checkpoint provided in this repo; are they expected to get the same number?
I don't revise the code except for 1).

Do you know any other possible ways to result in the accuracy drop?
Thanks for your help!

**Comment by lixinghe1999** [comment]
Same thing happened to Extended VGGSound

**Comment by swimmiing** [comment]
Thank you for your interest in our research. You've raised the issue where using the same pth file leads to varying outcomes.

For the extended dataset, it's worth verifying the sampling rate (we use 16kHz). Additionally, ensure that VGGSS has a sampling rate of 16kHz. Also, please confirm if the VGGSS test set consists of 5158 samples.

As **noted in the readme file in the VGGSS directory**, we've provided crucial information: the image frame corresponds to the 125th frame of a 25fps video. I'm uncertain about the configuration of the dataset from HuggingFace.

Many users of the VGGSS dataset tend to utilize the center frame of the video (the exact midpoint frame). However, this approach can lead to errors, which become noticeable when compared with annotations.

**Comment by lixinghe1999** [comment]
Dear Author,

Thank you for your reply.
1) my VGGSound test only contains 5121 files; although it is not good I believe it will only have a slight influence.
2) Looks like to the problem, I just checked the **0CEsVHHkwww_000030** file, and the ground truth bounding box is: "0CEsVHHkwww_000030", "class": "driving snowmobile", "bbox": [[**0.359375, 0.5125, 0.490625, 0.709375**]]
![0CEsVHHkwww_000030](https://github.com/swimmiing/ACL-SSL/assets/60444469/a5567400-781e-482f-bc4c-72b6c752b84d)
Seems like the box should be placed on the right side while the ground truth is not.

Further, I tried to solve it, however, after examining the video of VGGSound, I found "1. not all of them are 25FPS, can be 30FPS, 29.97FPS instead. 2. not all of them are 10 seconds long. As a result, can you further clarify how to select the frame?
My guess: We always select the 125th frame no matter the duration of the video or the FPS of the video.

**Comment by swimmiing** [comment]
You already check that file. That files should be like this. (Left below: Ground Truth, Right Top: Heatmap (ACL), Right Bottom: Binarized result)
![스크린샷 2024-03-25 오후 6 46 57](https://github.com/swimmiing/ACL-SSL/assets/47969204/e53a4acd-b446-465c-848b-912e895b7908)

It seems preferable to extract the frame corresponding to the time indicated by the 125th frame of the 25FPS. (No matter the duration of the video)

**Comment by ardasnck** [comment]
I assume the answers have solved your problem. I am closing the issue now.
